mkdir ../../active-speaker-detection/vad/vads
mkdir ../../active-speaker-detection/vad/audios
mkdir tracking_evaluation
mkdir tracking_evaluation/mot_challenge
mkdir tracking_evaluation/mot_challenge/seqmaps
mkdir tracking_evaluation/mot_challenge/mytrack-test
mkdir headbox_wearer_speaker
mkdir ../../active-speaker-detection/wearer/energy_based/energy
mkdir ../../active-speaker-detection/wearer/spectrogram/data/train_test_data
mkdir ../../active-speaker-detection/wearer/spectrogram/data/spectrograms
mkdir ../../active-speaker-detection/wearer/results
mkdir ../../active-speaker-detection/active_speaker/mrc_active_speaker_detection/prediction/results
mkdir ../../active-speaker-detection/active_speaker/active_speaker_evaluation/mAP_talknet/input/detection-results
mkdir ../../active-speaker-detection/active_speaker/active_speaker_evaluation/mAP_talknet/input/ground-truth
mkdir ../../active-speaker-detection/active_speaker/active_speaker_evaluation/mAP_mrc/input/detection-results
mkdir ../../active-speaker-detection/active_speaker/active_speaker_evaluation/mAP_mrc/input/ground-truth
mkdir ../../active-speaker-detection/audio_embedding/make_audio_embeddings/embeddings
mkdir ../../active-speaker-detection/audio_embedding/train/audios
mkdir ../../tracking/tracking_evaluation/data/gt
mkdir ../../tracking/tracking_evaluation/data/trackers/mot_challenge/mytrack-test/global/data
mkdir ../../tracking/tracking_evaluation/format_tracking_results/mot_format
mkdir ../../tracking/global_tracking/results
mkdir ../../tracking/people_detection/backup
mkdir ../../tracking/people_detection/obj
mkdir ../../active-speaker-detection/surrounding_people_audio_matching/results
